# Generated by Django 4.2.7 on 2023-12-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_date', models.DateTimeField(auto_created=True)),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField()),
                ('age', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
