# Generated by Django 4.2.7 on 2023-12-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
